# Generated by Django 6.1 on 2026-08-19 04:14

import accounts.fields
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_standingorder_amount_alter_transaction_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('customers_count', models.PositiveIntegerField(default=0)),
                ('accounts_count', models.PositiveIntegerField(default=0)),
                ('active_accounts', models.PositiveIntegerField(default=0)),
                ('inactive_accounts', models.PositiveIntegerField(default=0)),
                ('transactions_count', models.PositiveIntegerField(default=0)),
                ('total_deposits', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_withdrawals', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Deactivated customers are hidden from normal use but kept for record-keeping, instead of being hard-deleted.'),
        ),
        migrations.AddField(
            model_name='customer',
            name='nid',
            field=accounts.fields.EncryptedCharField(blank=True, help_text='Encrypted at rest, same as NID/PHONE in the Oracle schema.', max_length=255, verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=accounts.fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('annual_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate (%)', max_digits=5)),
                ('months', models.PositiveIntegerField(help_text='Loan term in months')),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('DEFAULTED', 'Defaulted')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='accounts.bankaccount')),
            ],
        ),
    ]
