# Generated by Django 6.1 on 2026-08-23 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_dailysnapshot_customer_is_active_customer_nid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Short branch code, e.g. DHK-01', max_length=20, unique=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='branch',
            field=models.ForeignKey(blank=True, help_text="Branch where this account is held. Defaults to the customer's branch if left blank.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='accounts.branch'),
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('SYSTEM_ADMIN', 'System Administrator'), ('BRANCH_MANAGER', 'Branch Manager'), ('BANK_OFFICER', 'Bank Officer'), ('TELLER', 'Teller'), ('LOAN_OFFICER', 'Loan Officer'), ('AUDITOR', 'Auditor')], default='TELLER', max_length=20)),
                ('employee_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Leave blank for Super Admin / System Administrator / Auditor roles, which are not tied to one branch.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='accounts.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
