# Generated by Django 6.1 on 2026-08-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_chartofaccount_journalentry_journalline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('INTEREST', 'Interest'), ('LOAN_DISBURSEMENT', 'Loan Disbursement')], max_length=20),
        ),
    ]
