# Generated by Django 6.1 on 2026-08-25 01:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_seed_chart_of_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(choices=[('WITHDRAW', 'Withdrawal'), ('TRANSFER', 'Transfer')], max_length=20)),
                ('fee_type', models.CharField(choices=[('FLAT', 'Flat Amount'), ('PERCENTAGE', 'Percentage of Amount')], default='FLAT', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, help_text='For FLAT: the fee in taka. For PERCENTAGE: the rate, e.g. 1.50 means 1.5% of the transaction amount.', max_digits=10)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['transaction_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee charged on top of amount, if any (see FeeRule).', max_digits=15),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reverses',
            field=models.OneToOneField(blank=True, help_text='If this is a compensating REVERSAL transaction, points to the original transaction it reverses. OneToOne so an original can only be reversed once.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_by', to='accounts.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='COMPLETED', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('INTEREST', 'Interest'), ('LOAN_DISBURSEMENT', 'Loan Disbursement'), ('REVERSAL', 'Reversal')], max_length=20),
        ),
    ]
