# Generated by Django 6.1 on 2026-08-28 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_customerportalaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Which rule(s) matched and why, for the reviewer.')),
                ('risk_score', models.PositiveIntegerField(help_text='0-100, higher = more suspicious.')),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('CONFIRMED_FRAUD', 'Confirmed Fraud'), ('FALSE_POSITIVE', 'False Positive')], default='PENDING_REVIEW', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_alerts_reviewed', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_alerts', to='accounts.transaction')),
            ],
            options={
                'ordering': ['-risk_score', '-created_at'],
            },
        ),
    ]
